### ISSUE TITLE
Build w/o encryption

### ISSUE THREAD

**Issue by RubenKelevra** [VTun/VTun#3]
Original Author: Kurt Werle
Original Date: 2000-04-10

I'm probably going to just tunnel vtun through ssh anyway - I'd like to build without needing the encryption libs.

**Comment by RubenKelevra** [comment]
Original Author: Max Krasnyansky
Original Date: 2000-05-11

Planed for 3.0

**Comment by bish0polis** [comment]
Due to the paper released by Jerome Etienne, claiming VTun was entirely insecure -- because it was tested and built without encryption for the test -- a build with no encryption isn't supported or (much) assisted.  Mr Etienne's similar app was mentioned as a more secure alternative, if I recall correctly, but may no longer be around.

It is possible, but the minute those accusations can be made valid the project loses any claim of security, and it's no longer a pressing goal.  

Thanks for approaching and asking for the history behind that.
